envs:
  client-api-dev:
    publish-to:
    - ecr-registry: 291042543057.dkr.ecr.us-east-1.amazonaws.com
      ecr-repository: demo-app-2022-api
      ecr-tag: $$$app-version
      semantic-versioning: true
      continue-on-error: true
      
    - ecr-registry: 291042543057.dkr.ecr.us-east-1.amazonaws.com
      ecr-repository: demo-app-2022-api
      ecr-tag: $$commit-hash
      unique-id: true
      
    - ecr-registry: 291042543057.dkr.ecr.us-east-1.amazonaws.com
      ecr-repository: demo-app-2022-api
      ecr-tag: dev
      force-push: true